# .travis.yml
osx_image: xcode9.1
language: generic
matrix:
  include:
    - os: osx
			env: TYPE=xcode
		- os: osx
			env: TYPE=spm
		- os: linux
			dist: xenial xerus
			sudo: required
			env: TYPE=spm
install: if [[ "$TYPE" == "spm" ]]; then eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"; fi
script: ./test
