# .travis.yml
osx_image: xcode9.1
language: swift
matrix:
  include:
    - os: osx
      env: TYPE=xcode
    - os: osx
      env: TYPE=spm
    - os: linux
      env: TYPE=spm
services:
  - docker
before_script:
  - docker run --detach -p 7419:7419 contribsys/faktory:0.6.0 -b :7419
  - |
    until nc -z -v -w30 127.0.0.1 7419
    do
      sleep 1
    done
script: ./test
