# .travis.yml
language: objective-c
sudo: required
matrix:
  include:
    - os: osx
      osx_image: xcode9.1
      env: TYPE=xcode
    - os: osx
      osx_image: xcode9.1
      env: TYPE=spm
    - os: linux
      dist: trusty
      sudo: required
      env: TYPE=spm
services:
  - docker
before_script:
  - docker run --detach -p 7419:7419 contribsys/faktory:0.6.1 -b :7419
  - |
    until nc -z -v -w30 127.0.0.1 7419
    do
      sleep 1
    done
script: ./test
